// ##### OP CODES ####
use crate::mos6502::*;

pub fn adc(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn and(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn asl(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn bcc(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn bcs(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn beq(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn bit(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn bmi(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn bne(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn bpl(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn brk(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn bvc(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn bvs(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn clc(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn cld(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn cli(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn clv(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn cmp(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn cpx(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn cpy(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn dec(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn dex(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn dey(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn eor(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn inc(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn inx(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn iny(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn jmp(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn jsr(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn lda(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn ldx(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn ldy(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn lsr(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn nop(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn ora(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn pha(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn php(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn pla(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn plp(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn rol(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn ror(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn rti(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn rts(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn sbc(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn sec(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn sed(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn sei(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn sta(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn stx(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn sty(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn tax(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn tay(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn tsx(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn txa(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn txs(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn tya(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
pub fn xxx(cpu: &mut Cpu, address_mode_values: AddressModeValues) {}
